version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/browser"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/core"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/oidc-dpop-client-browser"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/browser/examples/multi/bundle"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/browser/examples/single/native"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/packages/browser/examples/single/script"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/packages/browser/docs/api"
    schedule:
      interval: "daily"
