language: node_js
node_js:
  - "node"
script:
  - npm run test

sudo: required

services:
  - xvfb

addons:
  firefox: latest-beta
  chrome: beta

before_script:
  - npm run bootstrap
  - "export DISPLAY=:99.0"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &