name: CI

on: [push, workflow_dispatch]

env:
  CI: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Available OS's: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
        os: [ubuntu-20.04, windows-2019]
        node-version: [14.x, 12.x, 10.x]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run bootstrap -- --ci
      - run: npm run build
      - run: npm run test
      - # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
        # Since all the other jobs of this workflow depend on this one, skipping it should
        # skip the entire workflow.
        if: ${{ github.actor != 'dependabot' }}
        run: npm run e2e-test
        env: 
          E2E_TEST_REFRESH_TOKEN: ${{ secrets.E2E_TEST_REFRESH_TOKEN }}
          E2E_TEST_CLIENT_ID: ${{ secrets.E2E_TEST_CLIENT_ID }}
          E2E_TEST_CLIENT_SECRET: ${{ secrets.E2E_TEST_CLIENT_SECRET }}
          E2E_TEST_IDP_URL: ${{ secrets.E2E_TEST_IDP_URL }}
          E2E_TEST_ESS_POD: ${{ secrets.E2E_TEST_ESS_POD }}
      - run: npx prettier --check "{packages/*/src,packages/*/__tests__}/**"
      - run: npm audit --audit-level=moderate
      - run: npm run lerna-audit -- --audit-level=moderate
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.2.2
        continue-on-error: true
        with:
          name: code-coverage-report
          path: ./packages/*/coverage/
